// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN1TnS1ZbbjzmbC2CFxIZDpPIuQ7hhyvw',
    appId: '1:99492070089:web:972a93a0ff7113f64e4318',
    messagingSenderId: '99492070089',
    projectId: 'studyapp-3ddf7',
    authDomain: 'studyapp-3ddf7.firebaseapp.com',
    storageBucket: 'studyapp-3ddf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR1egsdI5pi01Ump_4w0ikDYFtXZb2M_8',
    appId: '1:99492070089:android:37dca2b146916dcd4e4318',
    messagingSenderId: '99492070089',
    projectId: 'studyapp-3ddf7',
    storageBucket: 'studyapp-3ddf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy-V14NBECFBbdIkQ2MCmokcHwjjntTbo',
    appId: '1:99492070089:ios:004554957733213a4e4318',
    messagingSenderId: '99492070089',
    projectId: 'studyapp-3ddf7',
    storageBucket: 'studyapp-3ddf7.appspot.com',
    iosBundleId: 'com.example.studyExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy-V14NBECFBbdIkQ2MCmokcHwjjntTbo',
    appId: '1:99492070089:ios:004554957733213a4e4318',
    messagingSenderId: '99492070089',
    projectId: 'studyapp-3ddf7',
    storageBucket: 'studyapp-3ddf7.appspot.com',
    iosBundleId: 'com.example.studyExam',
  );
}
